#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) {{ year }} mousse project

"""
Script

Description
"""


from __future__ import print_function, division


def _main():
    pass

if __name__ == '__main__':
    _main()
