#!/bin/sh
cd ${0%/*} || exit 1

# Parse arguments for library compilation
target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments

wmake-check-pwd "$WM_PROJECT_DIR/src" || {
    echo "allwmake error: Current directory is not \$WM_PROJECT_DIR/src"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the mousse entries in your dot-files and source them."
    exit 1
}

set -x

# Update mousse version strings if required
wmake-print-build -check || /bin/rm -f core/_make/*/global.? 2>/dev/null

wmake-lninclude -f core
wmake-lninclude -f os_specific/${WM_OSTYPE:-posix}
pstream/allwmake $target_type $*

os_specific/${WM_OSTYPE:-posix}/allwmake $*
wmake $target_type core

wmake $target_type file_formats
wmake $target_type surf_mesh
wmake $target_type tri_surface
wmake $target_type mesh_tools
wmake $target_type edge_mesh

# Decomposition methods needed by dummy_third_party
# (dummy metis_decomp, scotch_decomp etc) needed by e.g. mesh_tools
parallel/decompose/allwmake-lninclude
dummy_third_party/allwmake $target_type $*

wmake $target_type finite_volume
wmake $target_type lagrangian/basic
wmake $target_type lagrangian/distribution_models
wmake $target_type generic_patch_fields

wmake $target_type conversion
wmake $target_type sampling
wmake $target_type mesh/extrude_model
wmake $target_type dynamic_mesh
wmake $target_type dynamic_fv_mesh
wmake $target_type topo_changer_fv_mesh

# Compile scotch_decomp, metis_decomp etc.
parallel/allwmake $target_type $*

wmake $target_type ode
wmake $target_type random_processes

transport_models/allwmake $target_type $*
thermophysical_models/allwmake $target_type $*
turbulence_models/allwmake $target_type $*
wmake $target_type combustion_models
region_models/allwmake $target_type $*
lagrangian/allwmake $target_type $*
mesh/allwmake $target_type $*
renumber/allwmake $target_type $*
fv_agglomeration_methods/allwmake $target_type $*

wmake $target_type fv_motion_solver
wmake $target_type engine
wmake $target_type fv_options
wmake $target_type region_coupled

post_processing/allwmake $target_type $*

wmake $target_type six_dof_rigid_body_motion
