#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/run-functions

# Set application name
readonly APPLICATION=$(get_application)

run_application block-mesh
run_application $APPLICATION
run_application mousse-sample -latestTime

( cd validation && ./create_graphs )
