#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# 
# Script
#     wcleanAll
# Description
#     search all the directories below the current for the object file
#     directories of all machines and delete them.

Script=${0##*/}

usage() {
	exec 1>&2
	while [ "$#" -ge 1 ]; do echo "$1"; shift; done
	cat<<-USAGE
	Usage: $Script

	    Remove all object and related files

	USAGE
	exit 1
}

# Parse arguments and options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help | --help)
        usage
        ;;
    *)
        usage "unknown option/argument: '$*'"
        ;;
    esac
done

[ -d bin -a -d src ] || usage "not in the project top level directory"

echo "Removing platforms/sub-directories"
rm -rf platforms/*

echo "Cleaning _make sub-directories"
find . -depth \( -name _make -o -name "_make.[A-Za-z]*" \) -type d -print | \
    xargs -I {} find '{}' -mindepth 1 -maxdepth 1 -type d -print | \
    xargs rm -rf

echo "Removing _lninclude directories"
find . -depth -type d \( -name _lninclude \) -exec rm -rf {} \;

echo "Removing misc files"
find . \( -name exe -o -name log \) -exec rm {} \;

tutorials/Allclean

# Cleanup local variables and functions
unset Script usage

# vim: set ft=sh noet sw=4 ts=4 sts=4:
