#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# 
# Script
#     wclean-machine
# Description
#     Searches the directory tree starting at the current directory for the
#     object file directories of the specified machine type(s) and deletes them.
#     If a machine type is not provided the current machine type is assumed.
#
#     Usage: wclean-machine [ -current ]
#            wclean-machine <machineType> [ .. <machineTypeN> ]

Script=${0##*/}

usage() {
	exec 1>&2
	while [ "$#" -ge 1 ]; do echo "$1"; shift; done
	cat<<-USAGE
	Usage: $Script machineType [... machineTypeN] [ -current ]

	Searches the directory tree starting at the current directory for the
	object file directories of the specified machine type(s) and deletes them.
	If either -current or no machine type is specified then the current type
	is assumed (from $WM_OPTIONS).

	USAGE
	exit 1
}

# Print help message
if [ "$1" = "-h" -o "$1" = "-help" -o "$1" = "--help" ]
then
    usage
fi

# Get the machines from the arguments
machines="$@"

# If no arguments are provided default to current machine type
if [ "$#" -lt 1 ]
then
    machines="-current"
fi

# Loop over all the machine types specified and delete the object directories
for mach_type in $machines
do
    if [ "$mach_type" = "-current" ]
    then
        mach_type="$WM_OPTIONS"
        echo "Current machine type: $mach_type"
        [ -n "$mach_type" ] || continue
    fi

    echo "Cleaning machine type: $mach_type"

    find . -depth \( -name Make -o -name "_make.[A-Za-z]*" \) -type d -print | \
        xargs -I {} find '{}' -mindepth 1 -maxdepth 1 \
              \( -type d -name "*$mach_type" -o -name "*$mach_type$WM_MPLIB" \) \
              -print | xargs rm -rf

    rm -rf platforms/${mach_type}*

done

# Cleanup local variables and functions
unset Script machines

# vim: set ft=sh noet sw=4 ts=4 sts=4:
