#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# 
# Script
#     wclean-lninclude-all
# Description
#     Delete all the _lninclude directories in the tree.

Script=${0##*/}

# Default to the CWD
if [ "$#" -eq 0 ]
then
    set -- .
elif [ "$1" = "-h" -o "$1" = "-help" -o "$1" = "--help" ]
then
    echo "Usage: $Script [dir1] .. [dirN]"
    echo
    echo "    Delete all the _lninclude directories in the tree"
    echo
    exit 1
fi


for dir
do
    if [ -d "$dir" ]
    then
        echo "removing _lninclude directories: $dir"
        find $dir -depth -type d -name _lninclude -exec rm -rf {} \;
    else
        echo "no directory: $dir" 1>&2
    fi
done

# Cleanup local variables and functions
unset Script

# vim: set ft=sh noet sw=4 ts=4 sts=4:
