#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# 
# Script
#     wmake-files-and-options
#
# Description
#     Scan current directory for directories and source files
#     and construct Make/files and Make/options
#
#     Usage : wmake-files-and-options

Script=${0##*/}

usage() {
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat <<- USAGE

	Usage: $Script

		Scan current directory for directories and source files
		and construct 'Make/files' and 'Make/options'

	USAGE
    exit 1
}


# Parse arguments and options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help | --help)   # provide immediate help
        usage
        ;;
    -*)
        usage "unknown option: '$*'"
        ;;
    *)
        break
        ;;
    esac
done

# No arguments
[ "$#" -eq 0 ] || usage "unexpected arguments: '$*'"


# Check environment variables
for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
do
    eval test "\$$check" || {
        echo "$Script error: environment variable \$$check not set" 1>&2
        exit 1
    }
done

if [ -d _make ]
then
    echo "$Script error: _make directory already exists" 1>&2
    exit 1
else
    mkdir _make
fi

[ -e _make/files ] || {
    echo "$Script: Creating _make/files"
    $WM_DIR/scripts/make-files
}

[ -e _make/options ] || {
    echo "$Script: Creating _make/options"
    $WM_DIR/scripts/make-options
}

# Cleanup local variables and functions
unset Script usage

# vim: set ft=sh noet sw=4 ts=4 sts=4:
