#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# Script
#     wmake-check-pwd <dir>
#
# Description
#     Check that the current working directory is the directory <dir>

Script=${0##*/}

unset quiet_opt

usage() {
    [ "$quiet_opt" = true ] && exit 1
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat <<- USAGE

	Usage: $Script [OPTION] dirName

	options:
	  -q | -quiet   suppress all normal output

	Check that the current working directory is the directory <dir>

	Exit status 0 when the directories are identical
	Exit status 1 on error

	USAGE
	exit 1
}


# Parse arguments and options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help | --help)
        usage
        ;;
    -q | -quiet | --quiet)
        quiet_opt=true
        shift
        ;;
    -*)
        usage "unknown option: '$*'"
        ;;
    *)
        break
        ;;
    esac
done


[ "$#" -eq 1 ] || usage

# Set dir_name to <dir>
dir_name="$1"

# Simple check against $PWD
[ "$PWD" = "$dir_name" ] && exit 0

# Check existance of <dir>
[ -d "$dir_name" ] || {
    [ "$quiet_opt" = true ] || {
        echo "$Script error: Directory does not exist $dir_name"
    }
    exit 1
}

# Use /bin/pwd to get the absolute path (could be linked)
this_dir=$(/bin/pwd)
target=$(cd $dir_name 2>/dev/null && /bin/pwd)

# Return 0 if this directory is <dir>
[ "$this_dir" = "$target" ] && exit 0

# This directory is not <dir>
[ "$quiet_opt" = true ] || {
    echo "$Script error: Current directory is not $dir_name"
}
exit 1


# Cleanup local variables and functions

unset Script usage

# vim: set ft=sh noet sw=4 ts=4 sts=4:
