#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# Script
#     wrmdep [-a | -all | all] [file]
#
# Description
#     Remove all .dep files from the object directory tree corresponding to the
#     current source derectory or remove only the .dep files referring to the
#     optionally specified [file].  With the -a/-all/all option the .dep files
#     are removed for all platforms rather than just the current platform.

Script=${0##*/}

# Source the wmake functions
. ${0%/*}/scripts/wmake-functions

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat <<- USAGE
    Usage: $Script [-a | -all | --all | all] [file]

    Remove all .dep files or remove .dep files referring to <file>
    With the -a/-all/all option the .dep files are removed for all platform
    rather than just the current platform.

    USAGE
    exit 1
}

# Parse arguments and options
# Default to processing only the current platform
all=

while [ "$#" -gt 0 ]
do
    case "$1" in
        # Print help
        -h | -help | --help)
        usage
        ;;
        # Non-stop compilation, ignoring errors
        -a | -all | all | --all)
        all="all"
        shift
        ;;
    -*)
        usage "unknown option: '$*'"
        ;;
    *)
        break
        ;;
    esac
done

# Check environment variables
check_env

# Remove the selected .dep files from the object tree
find_object_dir .

# With the -a/-all option replace the current platform with a wildcard
if [ "$all" = "all" ]
then
    objects_dir=$(echo $objects_dir | sed s%$WM_OPTIONS%*% )
fi

if [ "$#" -eq 0 ]
then
    echo "removing all .dep files ..."
    find $objects_dir -name '*.dep' -print | xargs -t rm 2>/dev/null
else
    echo "removing .dep files referring to $1 ..."
    find $objects_dir -name '*.dep' -exec grep "$1" '{}' \; -exec rm '{}' \;
fi

# Cleanup local variables and functions
unset Script usage

# vim: set ft=sh noet sw=4 ts=4 sts=4:
