#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# Script
#     wrmo [-a | -all | all] [file]
#
# Description
#     Remove all .o files from the object directory tree corresponding to the
#     current source derectory or remove only the .o file corresponding to the
#     optionally specified [file].  With the -a/-all/all option the .o files
#     are removed for all platforms rather than just the current platform.

Script=${0##*/}

# Source the wmake functions
. ${0%/*}/scripts/wmakeFunctions

usage() {
	exec 1>&2
	while [ "$#" -ge 1 ]; do echo "$1"; shift; done
	cat <<- USAGE
	Usage: $Script [file]

	Remove all .o files or remove .o file corresponding to <file>

	USAGE
	exit 1
}

# Parse arguments and options

# Default to processing only the current platform
all=

while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help | --help)
        usage
        ;;
    # Non-stop compilation, ignoring errors
    -a | -all | all | --all)
        all="all"
        shift
        ;;
    -*)
       usage "unknown option: '$*'"
       ;;
    *)
       break
       ;;
    esac
done

# Check environment variables
check_env

# Remove the selected .o files from the object tree
find_object_dir .

# With the -a/-all option replace the current platform with a wildcard
if [ "$all" = "all" ]
then
    objects_dir=$(echo $objects_dir | sed s%$WM_OPTIONS%*% )
fi

if [ "$#" -eq 0 ]
then
    echo "removing all .o files ..."
    find $objects_dir -name '*.o' -print | xargs -t rm 2>/dev/null
else
    echo "removing .o files corresponding to $1 ..."
    rm $objects_dir/${1%%.*}.o
fi

# Cleanup local variables and functions
unset Script usage

# vim: set ft=sh noet sw=4 ts=4 sts=4:
