#!/bin/sh
# Copyright (C) 2011-2015 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
#
# Script
#   create_graphs
#
# Description
#   Creates .eps graphs of OpenFOAM results vs experiment for the buoyant
#   cavity case

create_eps_t()
{
  local index=$1
  local mousse=$2
  local expt=$3

  gnuplot<<EOF
  set terminal postscript eps color enhanced
  set output "mousse_vs_expt_T$i.eps"
  set xlabel "Channel width, x / [m]"
  set ylabel "Temperature / [K]"
  set grid
  set key left top
  set size 0.6, 0.6
  set xrange [0:0.08]
  set yrange [285:310]
  plot \
    "$expt" u (\$1/1000):(\$2+273.15) title "Expt 0.$index" \
    with points lt 1 pt 6, \
    "$mousse" title "mousse 0.$index" with lines linetype -1
EOF
}

create_eps_u()
{
  local index=$1
  local mousse=$2
  local expt=$3

  gnuplot<<EOF
  set terminal postscript eps color enhanced
  set output "mousse_vs_expt_U$i.eps"
  set xlabel "Channel width, x / [m]"
  set ylabel "Vertical velocity component, Uy / [m/s]"
  set grid
  set key left top
  set size 0.6, 0.6
  set xrange [0:0.08]
  set yrange [-0.2:0.2]
  plot \
      "$expt" u (\$1/1000):(\$2) title "Expt 0.$index" \
      with points lt 1 pt 6, \
      "$mousse" u 1:3 title "mousse 0.$index" with lines linetype -1
EOF
}

# test if gnuplot exists on the system
which gnuplot > /dev/null 2>&1 || {
  echo "gnuplot not found - skipping graph creation" >&2
  exit 1
}

SETSDIR="../postProcessing/sets"

[ -d $SETSDIR ] || {
  echo "create_graphs: results sets not available in directory $SETSDIR"
  exit 0
}

# paths to data
LATESTTIME=$(ls $SETSDIR)
MOUSSEDATAROOT=$SETSDIR/$LATESTTIME

EXPTDATAROOT=./expt_data

# generate temperature profiles
TSets="1 3 4 5 6 7 9"
for i in $TSets
do
    echo "    processing temperature profile at y/yMax of 0.$i" \
        > log.create_graphs 2>&1

    MOUSSE="$MOUSSEDATAROOT/y0.${i}_T.xy"
    EXPT="$EXPTDATAROOT/mt_z0_${i}0_lo.dat"

    create_eps_t $i $MOUSSE $EXPT
done


# generate velocity profiles
USets="1 3 4 5 6 7 9"
for i in $USets
do
    echo "    processing velocity profile at y/yMax of 0.$i" \
        > log.create_graphs 2>&1

    MOUSSE="$MOUSSEDATAROOT/y0.${i}_U.xy"
    EXPT="$EXPTDATAROOT/mv_z0_${i}0_lo.dat"

    create_eps_u $i $MOUSSE $EXPT
done

echo Done
