#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake-lninclude decomposition_methods
wmake-lninclude metis_decomp
wmake-lninclude scotch_decomp
wmake-lninclude ptscotch_decomp

# ----------------------------------------------------------------- end-of-file
