#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/clean-functions

# remove surface and features
\rm -f constant/triSurface/motorBike.obj.gz > /dev/null 2>&1
\rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
\rm -f constant/triSurface/motorBike.eMesh > /dev/null 2>&1

rm -rf 0 > /dev/null 2>&1

clean_case
