#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

SO_EXT=so
[ "$(uname -s)" = "Darwin" ] && SO_EXT=dylib

# Parse arguments for library compilation
target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments

# get METIS_VERSION, METIS_ARCH_PATH
if settings=`$WM_PROJECT_DIR/bin/mousse-etc-file config/metis.sh`
then
    . $settings
    echo "using METIS_ARCH_PATH=$METIS_ARCH_PATH"
    if [ -r "$METIS_ARCH_PATH/lib/libmetis.$SO_EXT" ]
    then
        wmake $target_type
    fi
else
    echo
    echo "Error: no config/metis.sh settings"
    echo
fi

unset SO_EXT
