#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/clean-functions

# remove surface
\rm -f constant/triSurface/propellerTip.obj.gz > /dev/null 2>&1
clean_case
\rm -rf 0 > /dev/null 2>&1
\rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
\rm -f constant/triSurface/*.eMesh* > /dev/null 2>&1
