#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments
set -x

wmake $target_type

# ----------------------------------------------------------------- end-of-file
