#!/bin/sh
cd ${0%/*} || exit 1

target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments
set -x

wmake $target_type distribution_models
wmake $target_type basic
wmake $target_type solid_particle
wmake $target_type intermediate
wmake $target_type turbulence
wmake $target_type spray
wmake $target_type dsmc
wmake $target_type coal_combustion

molecular_dynamics/allwmake $target_type $*
