#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/clean-functions

\rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
\rm -f constant/triSurface/rotatingZone.eMesh > /dev/null 2>&1
\rm -f constant/triSurface/fixed.eMesh > /dev/null 2>&1
\rm -f 0/pointLevel > /dev/null 2>&1
\rm -f 0/cellLevel > /dev/null 2>&1

clean_case
