#!/bin/sh
cd ${0%/*} || exit 1
set -x

wmake-lninclude interfacial_models
wmake-lninclude interfacial_composition_models
wmake libso phase_systems
wmake libso interfacial_models
wmake libso interfacial_composition_models
reacting-two-phase-euler/allwmake
reacting-multiphase-euler/allwmake
