#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

export COMPILE_FLAGS=''
export LINK_FLAGS=''

SO=so
[ "$(uname -s)" = "Darwin" ] && SO=dylib

if [ -f "${MOUSSE_LIBBIN}/libmousse_sloan_renumber.$SO" ]
then
    echo "Found libmousse_sloan_renumber.$SO  --  enabling Sloan renumbering support."
    export LINK_FLAGS="${LINK_FLAGS} -lmousse_sloan_renumber"
fi

wmake
