#!/bin/sh
cd ${0%/*} || exit 1

target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments
set -x

wmake $target_type potential
wmake $target_type molecular_measurements
wmake $target_type molecule
