#!/bin/sh
cd ${0%/*} || exit 1

target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments

wmake-check-pwd "$WM_PROJECT_DIR" || {
    echo "allwmake error: Current directory is not \$WM_PROJECT_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the mousse entries in your dot-files and source them."
    exit 1
}

(cd wmake/src && make)

src/allwmake $target_type $*

applications/allwmake $target_type $*

