#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/run-functions

readonly N_PROCS=$(get_number_of_processors)

mkdir -p 0

run_application block-mesh
cp system/decomposeParDict.hierarchical system/decomposeParDict
run_application decomposePar

cp system/decomposeParDict.ptscotch system/decomposeParDict
run_parallel snappy-hex-mesh $N_PROCS -overwrite

find . -type f -iname "*level*" -exec rm {} \;

ls -d processor* | xargs -I {} cp -r 0.org ./{}/0 $1

run_parallel topo-set $N_PROCS
run_parallel $(get_application) $N_PROCS

run_application reconstruct-par-mesh -constant
run_application reconstruct-par

# vim: set ft=sh noet sw=2 ts=2 sts=2:
