#!/bin/sh
set -x
cd ${0%/*} || exit 1    # Run from this directory

_so_ext=so
[ "$(uname -s)" = "Darwin" ] && _so_ext=dylib

# Parse arguments for library compilation
target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments

# get METIS_VERSION, METIS_ARCH_PATH
if settings=$($WM_PROJECT_DIR/bin/mousse-etc-file config/metis.sh)
then
    . $settings
    echo "using METIS_ARCH_PATH=$METIS_ARCH_PATH"
    _metis_lib=$METIS_ARCH_PATH/lib/libmetis.$_so_ext
    # RHEL-like
    [ ! -r $_metis_lib ] && _metis_lib=$METIS_ARCH_PATH/lib64/libmetis.$_so_ext
    # Debian
    [ ! -r $_metis_lib ] && _metis_lib=$METIS_ARCH_PATH/lib/x86_64-linux-gnu/libmetis.$_so_ext

    if [ -r "$_metis_lib" ]
    then
        wmake $target_type
    fi
else
    echo
    echo "Error: no config/metis.sh settings"
    echo
fi

unset _so_ext _metis_lib
set +x
