#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/run-functions

# Set application name
application=$(get_application)

run_application mousse-block-mesh
run_application $application
run_application mousse-calc components U
run_application mousse-sample
