#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# Script
#   make-target-dir
#
# Description
#   Makes a directory hierarchy for the given target file
#
#   Usage: make-target-dir <directory>
#
#------------------------------------------------------------------------------

for target
do
    dir=${target%/*}
    [ -d "$dir" ] || [ "$dir" = "$target" ] || mkdir -p "$dir"
done

# vim: set ft=sh noet sw=2 ts=2 sts=2:
