#!/bin/sh
# mousse: CFD toolbox
# Copyright (C) 2011-2014 OpenFOAM Foundation
# Copyright (C) 2016 mousse project
# 
# Script
#     wmake-functions
# Description
#     Functions to check wmake environment and find .dep and .o files

# Check environment variables
check_env()
{
	for envar in WM_OPTIONS WM_DIR WM_PROJECT_DIR
	do
		eval test "\$$envar" || {
		echo "$Script error: environment variable \$$envar not set" 1>&2
		exit 1
		}
	done
}


# Search up directories tree for the Make sub-directory
expand_path()
{
	if [ -d "$1" ]
	then
		ex_path=$(cd "$1" && pwd -P)
	else
		ex_path=$(cd $(dirname "$1") && pwd -P)
	fi
}

find_target()
{
	expand_path $1

	if [ "$ex_path" = "$WM_PROJECT_DIR" \
		-o "$exPath" = "$HOME" \
		-o "$exPath" = "/" \
		]
then
	echo "$Script error: could not find _make directory" 1>&2
	exit 1
elif [ -d "$1/_make" ]; then
	dir=$1
else
	find_target "$1/.."
fi
}

find_object_dir()
{
	expand_path $1

	if echo $ex_path | grep "$WM_PROJECT_DIR" > /dev/null
	then
		platform_path=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}
		objects_dir=$platformPath$(echo $exPath | sed s%$WM_PROJECT_DIR%% )
	else
		path=$ex_path
		dir=.
		if [ ! -d _make ]
		then
			find_target .
		fi
		app_dir=$dir
		expand_path $app_dir/.
		objects_dir=$app_dir/_make/${WM_OPTIONS}$(echo $path | sed s%$exPath%% )
	fi
}

dep_to_source()
{
	source_file=$(echo ${dep_file%.dep} | \
		sed -e s%platforms/${WM_OPTIONS}/%% -e s%_make/${WM_OPTIONS}/%% )
}

# vim: set ft=sh noet sw=2 ts=2 sts=2:
