#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/run-functions

# Get application name
readonly APPLICATION=$(get_application)

run_application block-mesh
run_application box-turb
run_application $APPLICATION
run_application enstrophy
