#!/bin/sh
cd ${0%/*} || exit 1

target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments
set -x

wmake $target_type liquid_properties
wmake $target_type liquid_mixture_properties
wmake $target_type solid_properties
wmake $target_type solid_mixture_properties
