#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/run-functions

application=$(getApplication)

runAnsysToFoam()
{
    if [ -f log.ansys-to-foam ]
    then
        echo "ansysToFoam already run on $PWD: remove log file to re-run"
    else
        echo "Running ansysToFoam: converting mesh $1"
        mousse-ansys-to-foam $1 -scale $2 > log.ansys-to-foam 2>&1
    fi
}

runAnsysToFoam flange.ans 0.001
runApplication $application
runApplication foam-to-ensight
runApplication foam-to-ensight-parts
runApplication foam-to-vtk -ascii
