#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/run-functions

readonly APPLICATION=$(get_application)

./make_mesh

run_application decompose-par
run_parallel $APPLICATION 4
run_application reconstruct-par
