#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
target_type=libo
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments $*

unset COMP_FLAGS LINK_FLAGS

#
# use <sys/inotify.h> if available (Linux)
#
if [ -f /usr/include/sys/inotify.h ]
then
    echo "Found <sys/inotify.h>  --  enabling inotify for file monitoring."
    export COMP_FLAGS="-DMOUSSE_USE_INOTIFY"
else
    unset COMP_FLAGS
fi

# make (non-shared by default) object
wmake $target_type

# ----------------------------------------------------------------- end-of-file
