#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/run-functions

# Get application name
readonly APPLICATION=$(get_application)

run_application block-mesh

# Create faceZones for baffles and fan
run_application topo-set

cp -r 0.org 0

# Create wall and cyclic baffles and the fields on them
run_application create-baffles -overwrite

run_application $APPLICATION
