#!/bin/sh
cd ${0%/*} || exit 1

target_type=libso
. $WM_PROJECT_DIR/wmake/scripts/allwmake-parse-arguments
set -x

wmake ${1:-libo} post_calc
wmake $target_type mousse_calc_functions

function_objects/allwmake $target_type $*
